//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Lecturer
    {
        public int ID { get; set; }
        public Nullable<int> Slot { get; set; }
        public int ClassID { get; set; }
        public int LecturerID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}
