//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Class_Lecturer = new HashSet<Class_Lecturer>();
            this.Students = new HashSet<Student>();
        }
    
        public int ID { get; set; }
        public string ClassName { get; set; }
        public int UniversityID { get; set; }
        public string MainLecCode { get; set; }
    
        public virtual University University { get; set; }
        public virtual ICollection<Class_Lecturer> Class_Lecturer { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
