//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Lecturer_Subjects = new HashSet<Lecturer_Subjects>();
            this.Prequisites = new HashSet<Prequisite>();
            this.Prequisites1 = new HashSet<Prequisite>();
            this.Student_Subjects = new HashSet<Student_Subjects>();
        }
    
        public int ID { get; set; }
        public string SubCode { get; set; }
        public string SubName { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> TotalSlots { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Lecturer_Subjects> Lecturer_Subjects { get; set; }
        public virtual ICollection<Prequisite> Prequisites { get; set; }
        public virtual ICollection<Prequisite> Prequisites1 { get; set; }
        public virtual ICollection<Student_Subjects> Student_Subjects { get; set; }
    }
}
