//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking.Data.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KPI
    {
        public int kpiID { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> kpiNumber { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
