//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking.Data.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account
    {
        public string accountId { get; set; }
        public string teamID { get; set; }
        public string accountPass { get; set; }
        public string accountName { get; set; }
        public string aPhone { get; set; }
        public string aFBurl { get; set; }
        public string aAddress { get; set; }
        public string aCMND { get; set; }
        public Nullable<int> aRoleId { get; set; }
        public string aEmail { get; set; }
        public Nullable<bool> aIsMale { get; set; }
    
        public virtual tbl_Team tbl_Team { get; set; }
    }
}
