//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viking.Data.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public string note { get; set; }
        public Nullable<int> cusID { get; set; }
        public string curAdminId { get; set; }
        public string teamID { get; set; }
        public Nullable<int> proID { get; set; }
        public Nullable<double> loanAmounth { get; set; }
        public Nullable<int> stageID { get; set; }
        public string history { get; set; }
        public string referenceSource { get; set; }
        public Nullable<int> campainID { get; set; }
    
        public virtual tbl_Campain tbl_Campain { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_Stage tbl_Stage { get; set; }
        public virtual tbl_Team tbl_Team { get; set; }
    }
}
